spring:
  application:
    name: spring
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

graphql:
  playground:
    enabled: true

